networks:
  monitor-net:
    driver: bridge

services:
  nats:
    image: nats:alpine
    # image: nats:2.9.20-alpine
    container_name: nats
    restart: always
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - ./ssl:/etc/nats/ssl
      - $JETSTREAM_STORAGE:/data
    networks:
      - monitor-net

  tcpdump:
    image: nicolaka/netshoot
    depends_on:
      - nats
    command: tcpdump -i eth0 -w /tcpdump-data/nats.pcap
    network_mode: service:nats
    volumes:
      - ./storage/tcpdump:/tcpdump-data

  nginx:
    image: nginx
    ports:
      - "4223:4223"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - nats
    networks:
      - monitor-net
